import React from "react";
import ReactDOM from "react-dom";
import "jquery";
// import "popper.js/dist/umd/popper";
// import "bootstrap/dist/js/bootstrap";
import "bootstrap/dist/css/bootstrap.css";
import NavBar from "./NavBar";
import App from "./App";
import "./index.css";
import "font-awesome/css/font-awesome.css";
// var element = <button class="btn btn-danger">Hello world</button>;
ReactDOM.render(<App></App>, document.getElementById("root"));
